### ISSUE TITLE
slf4j error

### ISSUE THREAD

**Issue by llamafilm** [Netflix/photon#366]
I tried running the included Dockerfile and got this error:

```
% docker build -t photon . 
% docker run --rm -v ./IMF/:/IMF photon IMPAnalyzer /IMF/colorbars
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.netflix.imflibrary.app.IMPAnalyzer.<clinit>(IMPAnalyzer.java:55)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```

I'm not a java developer so I don't know the implications of this, but I fixed it by adding `slf4j-simple` as a dependency: https://github.com/llamafilm/photon/commit/41015cf9c7e8cadcf8c335d2a2114553023dbe58

**Comment by fschleich** [comment]
Thanks - this has been addressed via #375
